
version: 2

models:
  - name: customers
    description: "Our starting query for customer oder count and first order date"
    columns:
      - name: customer_id
        description: "Customer ID - the primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Customer name"
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email"
        tests:
          - not_null
      - name: n_orders
        description: "Number of orders placed"
      - name: first_order_at
        description: "Date of first order"

  - name: customer_count
    description: "Counts total number of customers in the customer query"
    columns:
      - name: customer_count
        description: "Customer count"
        tests:
          - not_null
